/**
 * launcher Node acceptance — the fast, device-free checkpoint for the launcher: its pure modules
 * and stores, and its screens and the whole `LauncherRoot` rendered under `react-test-renderer`
 * over in-memory native shims (`native-host.tsx`, `native-storage.ts`). Every suite is run from
 * here and nowhere else. The on-device walk is `acceptance.spec.md`.
 *
 *   npm run launcher:test
 */

import { Harness } from './harness';
import { runLauncherInteractionTests } from './launcher-interactions.suite';
import { runScreenControlTests } from './screen-controls.suite';
import { runSettingsScreenTests } from './settings-screen.suite';
import { runBackPolicyTests } from './back-policy.suite';
import { runAppIndexTests } from './app-index.suite';
import { runStoreAccessTests } from './store-access.suite';
import { runPromptEnvelopeTests } from './prompt-envelope.suite';
import { runSeedTests } from './seed.suite';
import { runProductVerbsTests } from './product-verbs.suite';
import { runDevProbeBackButtonTests } from './dev-probe-back-button.suite';
import { runUnmountTeardownTests } from './unmount-teardown.suite';
import { runDeliverTests } from './deliver.suite';
import { runHistoryLogicTests } from './history-logic.suite';
import { runSharedStorageTests } from './shared-storage.suite';
import { runPromptFlowScreensTests } from './prompt-flow-screens.suite';
import { runGenerationClientTests } from './generation-client.suite';
import { runServerProbeTests } from './server-probe.suite';
import { runConnectivityTests } from './connectivity.suite';
import { runConnectivityUxTests } from './connectivity-ux.suite';
import { runSettingsProbeTests } from './settings-probe.suite';
import { runPromptFlowWiringTests } from './prompt-flow-wiring.suite';
import { runGenerationRequestTests } from './generation-request.suite';
import { runXhrTransportTests } from './xhr-transport.suite';
import { runWhimProseTests } from './whim-prose.suite';
import { runTileColourTests } from './tile-colour.suite';
import { runOrbMenuTests } from './orb-menu.suite';
import { runLoggingTests } from '../../logging/test/logging.suite';
import { runDiagnosticsTests } from '../../logging/test/diagnostics.suite';
import { runObservabilityUiTests } from './observability-ui.suite';
import { runFailureScreenTests } from './failure-screen.suite';
import { runPendingBuildsTests } from './pending-builds.suite';
import { runBuildLifecycleTests } from './build-lifecycle.suite';
import { runBundleValidityTests } from './bundle-validity.suite';
import { runGridCompositionTests } from './grid-composition.suite';
import { runRunJournalTests } from './run-journal.suite';
import { runRunSignalsTests } from './run-signals.suite';
import { runRunTimelineTests } from './run-timeline.suite';
import { runAppBusyTests } from './app-busy.suite';
import { runBootStateTests } from './boot-state.suite';
import { runHistoryWaitTests } from './history-wait.suite';
import { runAiConsentTests } from './ai-consent.suite';
import { runTermsAcceptanceTests } from './terms-acceptance.suite';
import { runAppLinkTests } from './app-link.suite';
import { runTransportSharedTests } from './transport-shared.suite';
import { runServiceRefusalTests } from './service-refusal.suite';
import { runRefusalLandingTests } from './refusal-landing.suite';
import { runReportPayloadTests } from './report-payload.suite';
import { runLinkRoutingTests } from './link-routing.suite';
import { runAppLinkUiTests } from './app-link-ui.suite';
import { runMiniAppDeliveryTests } from './mini-app-delivery.suite';
import { runForkUiTests } from './fork-ui.suite';
import { runConsentGateUiTests } from './consent-gate-ui.suite';
import { runErrorReasonTests } from './error-reason.suite';
import { runReportSendTests } from './report-send.suite';
import { runScreenExitsTests } from './screen-exits.suite';
import { runSchemeHostTests } from './scheme-host.suite';
import { runPromptFlowUiTests } from './prompt-flow-ui.suite';
import { runAttemptLifecycleUiTests } from './attempt-lifecycle-ui.suite';
import { runMiniAppHostUiTests } from './mini-app-host-ui.suite';
import { runHomeGridUiTests } from './home-grid-ui.suite';
import { runFlowScreensUiTests } from './flow-screens-ui.suite';
import { runHistoryUiTests } from './history-ui.suite';
import { runAppInfoTests } from './app-info.suite';
import { runRequestEnvelopeUiTests } from './request-envelope-ui.suite';
import { runTermsFlowUiTests } from './terms-flow-ui.suite';
import { runPrivacySettingsUiTests } from './privacy-settings-ui.suite';
import { runLegalLanguageTests } from './legal-language.suite';
import { runLegalLanguageUiTests } from './legal-language-ui.suite';
import { runAgeCheckTests } from './age-check.suite';
import { runAgeSignalUiTests } from './age-signal-ui.suite';
import { runDiagnosticsUiTests } from './diagnostics-ui.suite';
import { runWireFutureFramesTests } from './wire-future-frames.suite';
import { runFlowMessagesUiTests } from './flow-messages-ui.suite';
import { runKeyboardShellUiTests } from './keyboard-shell-ui.suite';

const h = new Harness();

console.log('\nlauncher acceptance\n');

await runBackPolicyTests(h);
await runAppIndexTests(h);
await runStoreAccessTests(h);
await runPromptEnvelopeTests(h);
await runSeedTests(h);
await runProductVerbsTests(h);
await runDevProbeBackButtonTests(h);
await runUnmountTeardownTests(h);
await runDeliverTests(h);
await runHistoryLogicTests(h);
await runSharedStorageTests(h);
await runPromptFlowScreensTests(h);
await runGenerationClientTests(h);
await runServerProbeTests(h);
await runConnectivityTests(h);
await runConnectivityUxTests(h);
await runSettingsProbeTests(h);
await runSettingsScreenTests(h);
await runPromptFlowWiringTests(h);
await runGenerationRequestTests(h);
await runXhrTransportTests(h);
await runWhimProseTests(h);
await runTileColourTests(h);
await runOrbMenuTests(h);
await runLoggingTests(h);
await runDiagnosticsTests(h);
await runObservabilityUiTests(h);
await runFailureScreenTests(h);
await runPendingBuildsTests(h);
await runBuildLifecycleTests(h);
await runBundleValidityTests(h);
await runGridCompositionTests(h);
await runRunJournalTests(h);
await runRunSignalsTests(h);
await runRunTimelineTests(h);
await runAppBusyTests(h);
await runBootStateTests(h);
await runHistoryWaitTests(h);
await runAiConsentTests(h);
await runTermsAcceptanceTests(h);
await runAppLinkTests(h);
await runTransportSharedTests(h);
await runServiceRefusalTests(h);
await runRefusalLandingTests(h);
await runReportPayloadTests(h);
await runLinkRoutingTests(h);
await runAppLinkUiTests(h);
await runMiniAppDeliveryTests(h);
await runForkUiTests(h);
await runConsentGateUiTests(h);
await runErrorReasonTests(h);
await runReportSendTests(h);
await runScreenExitsTests(h);
await runScreenControlTests(h);
await runLauncherInteractionTests(h);
await runSchemeHostTests(h);
await runPromptFlowUiTests(h);
await runAttemptLifecycleUiTests(h);
await runMiniAppHostUiTests(h);
await runHomeGridUiTests(h);
await runFlowScreensUiTests(h);
await runHistoryUiTests(h);
await runAppInfoTests(h);
await runRequestEnvelopeUiTests(h);
await runTermsFlowUiTests(h);
await runPrivacySettingsUiTests(h);
await runLegalLanguageTests(h);
await runLegalLanguageUiTests(h);
await runAgeCheckTests(h);
await runAgeSignalUiTests(h);
await runDiagnosticsUiTests(h);
await runWireFutureFramesTests(h);
await runFlowMessagesUiTests(h);
await runKeyboardShellUiTests(h);

console.log(`\n${h.passed} checks passed, ${h.failures.length} failed.`);
if (h.failures.length) {
  console.error('\nFAILURES:\n' + h.failures.map(f => '  - ' + f).join('\n'));
  process.exit(1);
}
console.log('✅ launcher acceptance green.\n');
