/**
 * What `npm run tokens` writes from `src/design/tokens.ts`, and the drift check `--check` runs
 * (design-system-v1 D1). Pure: every function takes the current file text and returns text, so
 * the CLI (`scripts/design-tokens.mjs`) owns the disk and the gate suite
 * (`checks/test/repo/design-system.suite.ts`) can run the same check on edited copies.
 *
 * Two kinds of output:
 *   - whole files, rewritten entirely (`palette.json`, `generated/springs.ts`, `generated/page.mjs`);
 *   - marked regions inside hand-written files: the lines between a line containing
 *     `tokens:begin <name>` and one containing `tokens:end <name>` (any comment syntax, e.g.
 *     `<!-- tokens:begin roles -->` in Markdown, `// tokens:begin mockup` in a script).
 */

import {
  COLORS,
  CONTRAST_RULES,
  EMBER_ROLES,
  GLOW,
  LAYOUT,
  NEUTRAL_ROLES,
  ON_PLATE,
  ON_TINT,
  RADII,
  SDK_SPACE,
  SHADOWS,
  SPACE,
  SPRINGS,
  STATUS,
  STATUS_NAMES,
  TILE_RIM,
  TIMINGS,
  TINT_NAMES,
  TINT_SOFT,
  TINTS,
  TOP_HIGHLIGHT,
  TYPE_SCALE,
  type ColorRole,
  type Pair,
  type Scheme,
  type Spring,
  type SpringName,
} from '../../src/design/tokens';
import { contrastRatio, deltaE, mixHex } from '../../src/design/tints';

export const SYSTEM_MD = 'docs/design/system.md';
export const MOCKUP_HTML = 'docs/design/mockups/index.html';
export const PALETTE_JSON = 'docs/design/system-v1/palette.json';
export const SPRINGS_TS = 'src/design/generated/springs.ts';
export const PAGE_MJS = 'src/design/generated/page.mjs';

const GENERATED_BY = 'Generated by `npm run tokens` (scripts/design-tokens.mjs) from src/design/tokens.ts. Do not edit.';

// ── Formatting ───────────────────────────────────────────────────────────────

const code = (s: string | number) => '`' + s + '`';
const fixed = (n: number, digits: number) => n.toFixed(digits);

/** A Markdown table row; an empty cell renders as a single space, as hand-written tables do. */
const row = (cells: readonly (string | number)[]) => '|' + cells.map((c) => (c === '' ? ' ' : ` ${c} `)).join('|') + '|';
const header = (cells: readonly string[]) => [row(cells), '|' + cells.map(() => '---').join('|') + '|'];

/** `a` / `b`, or `a` both when the two schemes agree. */
const pairCell = (p: Pair) => (p.light === p.dark ? `${code(p.light)} both` : `${code(p.light)} / ${code(p.dark)}`);

function signedEm(n: number): string {
  if (n === 0) return '0';
  return (n < 0 ? '−' : '+') + fixed(Math.abs(n), 3);
}

// ── Contrast ─────────────────────────────────────────────────────────────────

/** The lowest contrast of `fg` over `on` in `scheme`. */
function minContrast(scheme: Scheme, fg: ColorRole, on: readonly ColorRole[]): number {
  return Math.min(...on.map((bg) => contrastRatio(COLORS[scheme][fg], COLORS[scheme][bg])));
}

/** "4.66 / 5.97 on `bg`, `fill`" for the rule on `fg`, or '' when §2 specifies none. */
function contrastCell(fg: ColorRole): string {
  const rule = CONTRAST_RULES.find((r) => r.fg === fg);
  if (rule === undefined) return '';
  const at = rule.on.length > 1 ? '≥ ' : '';
  const [l, d] = (['light', 'dark'] as const).map((s) => at + fixed(minContrast(s, fg, rule.on), 2));
  return `${l} / ${d} on ${rule.on.map(code).join(', ')}`;
}

// ── system.md tables ─────────────────────────────────────────────────────────

function rolesTable(): string[] {
  const value = (v: string, material: string | undefined) => (material ? `${code(v)} ${material}` : code(v));
  return [
    ...header(['Role', 'Light', 'Dark', 'Use', 'Contrast']),
    ...Object.entries(NEUTRAL_ROLES).map(([role, spec]) => {
      const material = 'material' in spec ? spec.material : undefined;
      const contrast = role === 'text-3' ? 'Exempt (disabled)' : contrastCell(role as ColorRole);
      return row([code(role), value(spec.light, material?.light), value(spec.dark, material?.dark), spec.use, contrast]);
    }),
  ];
}

function emberTable(): string[] {
  return [
    ...header(['Role', 'Light', 'Dark', 'Notes']),
    ...Object.entries(EMBER_ROLES).map(([role, spec]) => {
      const contrast = contrastCell(role as ColorRole);
      return row([code(role), code(spec.light), code(spec.dark), contrast ? `${spec.use}; ${contrast}` : spec.use]);
    }),
    row([
      '`glow-core` / `glow-mid` / `glow-edge`',
      [GLOW.core, GLOW.mid, GLOW.edge].map(code).join(' / '),
      'same',
      'The light itself. Never carries text, never marks state',
    ]),
  ];
}

function statusTable(): string[] {
  return [
    ...header(['Role', 'Fill light / dark', 'On fill', 'Text light / dark', 'Soft light / dark', 'Icon']),
    ...STATUS_NAMES.map((name) => {
      const s = STATUS[name];
      return row([code(name), pairCell(s.fill), pairCell(s.on), pairCell(s.text), pairCell(s.soft), code(s.icon)]);
    }),
  ];
}

/** The reserved colours a tint must keep away from in `scheme`: every status fill and text form and
 *  the ember and its text form, each distinct value once. */
export function reservedColors(scheme: Scheme): Record<string, string> {
  const out: Record<string, string> = {};
  const add = (name: string, value: string) => {
    if (!Object.values(out).includes(value)) out[name] = value;
  };
  for (const name of STATUS_NAMES) {
    add(name, STATUS[name].fill[scheme]);
    add(`${name}-text`, STATUS[name].text[scheme]);
  }
  add('ember', EMBER_ROLES.ember[scheme]);
  add('ember-text', EMBER_ROLES['ember-text'][scheme]);
  return out;
}

/** The dark-mode tile rim colour of a tint. */
export const tileRim = (t: Pair) => mixHex(t.dark, t.light, TILE_RIM.mix);

/** The soft tint wash of `value` in `scheme`. */
export const tintSoft = (scheme: Scheme, value: string) => mixHex(value, COLORS[scheme][TINT_SOFT[scheme].over], TINT_SOFT[scheme].alpha);

function nearestReserved(scheme: Scheme, value: string): number {
  return Math.min(...Object.values(reservedColors(scheme)).map((r) => deltaE(value, r)));
}

function tintsTable(): string[] {
  return [
    ...header([
      'Tint',
      'Light',
      'Dark',
      'ΔE2000 to nearest reserved colour, light / dark (normal vision)',
      'White on light',
      'Ink on dark',
      'Dark rim on dark `bg`',
    ]),
    ...TINT_NAMES.map((name) => {
      const t = TINTS[name];
      return row([
        code(name),
        code(t.light),
        code(t.dark),
        `${fixed(nearestReserved('light', t.light), 1)} / ${fixed(nearestReserved('dark', t.dark), 1)}`,
        fixed(contrastRatio(t.light, ON_TINT.light), 2),
        fixed(contrastRatio(t.dark, ON_TINT.dark), 2),
        fixed(contrastRatio(tileRim(t), COLORS.dark.bg), 2),
      ]);
    }),
  ];
}

function typeTable(): string[] {
  return [
    ...header(['Token', 'Size / line', 'Weight', 'Tracking', 'Shell use', 'SDK `Text size`']),
    ...Object.entries(TYPE_SCALE).map(([token, t]) =>
      row([
        code(token),
        `${t.size} / ${t.lineHeight}`,
        t.headerWeight === undefined ? t.weight : `${t.weight} (${t.headerWeight} headers)`,
        signedEm(t.tracking),
        t.use,
        t.sdk === undefined ? '' : code(t.sdk),
      ]),
    ),
  ];
}

function spaceTable(): string[] {
  const steps = Object.keys(SPACE);
  const sdkByPt = new Map<number, string>(Object.entries(SDK_SPACE).map(([name, pt]) => [pt, name]));
  return [
    ...header(['Step', ...steps]),
    row(['pt', ...Object.values(SPACE)]),
    row(['SDK', ...Object.values(SPACE).map((pt) => (sdkByPt.has(pt) ? code(sdkByPt.get(pt) ?? '') : ''))]),
  ];
}

function layoutTable(): string[] {
  const L = LAYOUT;
  return [
    ...header(['Constant', 'Value']),
    row(['Screen gutter', L.gutter]),
    row(['Card padding', `${L.cardPadding} (${L.cardPaddingHero} hero)`]),
    row([
      'List row',
      `min ${L.listRowMinHeight}, padding ${L.listRowPaddingVertical} × ${L.listRowPaddingHorizontal}, separator inset ${L.separatorInset} (${L.separatorInsetWithIcon} with icons)`,
    ]),
    row([
      'Gaps',
      `${L.gapInGroup} inside a group, ${L.gapBetweenGroups} between groups, ${L.gapBetweenSections} between sections, ${L.gapTitleToSubtitle} title to subtitle, ${L.gapTitleToContent} title block to content`,
    ]),
    row([
      'Bottom action area',
      `${L.actionAreaTop} above the buttons, ${L.actionAreaBottom} below plus the safe area, ≥ ${L.actionAreaBottomNoInset} with no inset`,
    ]),
    row([
      'Button height',
      `${L.buttonHeight.large} large, ${L.buttonHeight.medium} medium, ${L.buttonHeight.small} small visual with a ${L.touchTarget.ios} target`,
    ]),
    row([
      'Touch target',
      `${L.touchTarget.ios} pt iOS, ${L.touchTarget.android} dp Android. Shell: \`hitSlop\` when the visual is smaller (${L.minHitVisual} min); adjacent small buttons keep ${L.smallTargetGap} between targets. SDK: real padding (the DOM has no hit-slop)`,
    ]),
  ];
}

function shapeTable(): string[] {
  return [...header(['Token', 'Radius', 'Use']), ...Object.entries(RADII).map(([name, r]) => row([code(`r-${name}`), r.radius, r.use]))];
}

function shadowsTable(): string[] {
  return [
    ...header(['Shadow', 'Light', 'Dark']),
    ...Object.entries(SHADOWS).map(([name, s]) => row([code(name), code(s.light), s.dark === s.light ? 'same' : code(s.dark)])),
  ];
}

function springsTable(): string[] {
  return [
    ...header(['Spring', 'Response', 'ζ', 'Stiffness', 'Damping', '95% / settled', 'Use']),
    ...(Object.entries(SPRINGS) as [SpringName, Spring][]).map(([name, s]) => {
      const sampled = sampleSpring(s);
      const overshoot = sampled.overshoot >= 0.01 ? `, ${fixed(sampled.overshoot * 100, 1)}% overshoot` : '';
      return row([
        code(name),
        fixed(s.response, 2),
        fixed(s.dampingRatio, 2),
        fixed(s.stiffness, 1),
        fixed(s.damping, 2),
        `${sampled.t95Ms} / ${sampled.durationMs} ms${overshoot}`,
        s.use,
      ]);
    }),
  ];
}

function timingsTable(): string[] {
  const T = TIMINGS;
  return [
    ...header(['Timing', 'Value', 'Use']),
    row(['`fade-in` / `fade-out`', `${T.fadeIn} / ${T.fadeOut} ms, ${code(T.fadeEasing)}`, 'Content swaps, reduced-motion replacements']),
    row(['`color`', `${T.color} ms, ${code(T.colorEasing)}`, 'Colour and tint changes']),
    row(['`stagger`', `${T.staggerPerItem} ms per item, first ${T.staggerFirst}, the rest together`, 'First appearance of a set only']),
    row([
      '`breathe`',
      `${T.breatheCycle} ms cycle, opacity ${T.breatheOpacity.from}–${T.breatheOpacity.to}, after ${T.breatheDelay} ms`,
      'Skeletons for local loads',
    ]),
  ];
}

// ── The mockup's token block ─────────────────────────────────────────────────

/** The mockup's CSS custom property for each role it draws. */
const MOCKUP_VARS: Readonly<Record<string, string>> = {
  separator: '--w-sep',
  'text-2': '--w-text2',
  'text-3': '--w-text3',
  positive: '--w-pos',
  'positive-text': '--w-pos-text',
  'positive-soft': '--w-pos-soft',
  warning: '--w-warn',
  'warning-text': '--w-warn-text',
  'warning-soft': '--w-warn-soft',
};

const jsString = (s: string) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const plain = (s: string) => s.replace(/\*\*|`/g, '');

function mockupBlock(): string[] {
  const roles: [string, Pair, string][] = [
    ...Object.entries(NEUTRAL_ROLES)
      .filter(([role]) => role !== 'scrim')
      .map(([role, spec]): [string, Pair, string] => [role, spec, spec.use]),
    ...Object.entries(EMBER_ROLES).map(([role, spec]): [string, Pair, string] => [role, spec, spec.use]),
    ...STATUS_NAMES.flatMap((name): [string, Pair, string][] => [
      [name, STATUS[name].fill, STATUS[name].use.fill],
      [`${name}-text`, STATUS[name].text, STATUS[name].use.text],
      [`${name}-soft`, STATUS[name].soft, STATUS[name].use.soft],
    ]),
  ];
  const pair = (p: Pair) => `[${jsString(p.light)}, ${jsString(p.dark)}]`;
  return [
    '  // [token, css var, light, dark, use]',
    '  roles: [',
    ...roles.map(([role, p, use]) => {
      const cells = [role, MOCKUP_VARS[role] ?? '--w-' + role, p.light, p.dark, plain(use)];
      return `    [${cells.map(jsString).join(', ')}],`;
    }),
    '  ],',
    '  // Same in both schemes. The glow stops decorate the ember mark and never mark state.',
    `  glow: { core: ${jsString(GLOW.core)}, mid: ${jsString(GLOW.mid)}, edge: ${jsString(GLOW.edge)}, ember: ${jsString(GLOW.halo)} },`,
    `  scrim: ${pair(NEUTRAL_ROLES.scrim)},`,
    `  shadowRaised: ${pair(SHADOWS['shadow-raised'])},`,
    `  shadowFloat: ${pair(SHADOWS['shadow-floating'])},`,
    `  highlight: ${pair({ light: 'inset 0 1px 0 ' + TOP_HIGHLIGHT.light, dark: 'inset 0 1px 0 ' + TOP_HIGHLIGHT.dark })},`,
    '  // App tints. Light value: fill, text, marks and tile plate in light mode, white label. Dark value:',
    '  // fill, text and marks in dark mode, ink label. Proof: palette-check.py.',
    '  tints: [',
    ...TINT_NAMES.map((name) => `    [${jsString(name)}, ${jsString(TINTS[name].light)}, ${jsString(TINTS[name].dark)}],`),
    '  ],',
    `  onTint: ${pair(ON_TINT)},`,
    `  onPlate: ${jsString(ON_PLATE)}, // the tile glyph, white on the light value in both schemes`,
  ];
}

// ── Whole files ──────────────────────────────────────────────────────────────

/** The palette proof's input (`palette-check.py` reads it; it holds no value of its own). */
function paletteJson(): string {
  const surfaces = (scheme: Scheme, roles: readonly ColorRole[]) => Object.fromEntries(roles.map((r) => [r, COLORS[scheme][r]]));
  const palette = {
    generatedBy: GENERATED_BY,
    tints: Object.fromEntries(TINT_NAMES.map((n) => [n, [TINTS[n].light, TINTS[n].dark]])),
    reservedLight: reservedColors('light'),
    reservedDark: reservedColors('dark'),
    white: ON_TINT.light,
    ink: ON_TINT.dark,
    light: surfaces('light', ['bg', 'surface', 'fill']),
    dark: surfaces('dark', ['bg', 'surface', 'raised', 'fill']),
    soft: {
      light: { alpha: TINT_SOFT.light.alpha, over: COLORS.light[TINT_SOFT.light.over] },
      dark: { alpha: TINT_SOFT.dark.alpha, over: COLORS.dark[TINT_SOFT.dark.over] },
    },
    rimMix: TILE_RIM.mix,
  };
  return JSON.stringify(palette, null, 2) + '\n';
}

function springsTs(): string {
  const entries = (Object.entries(SPRINGS) as [SpringName, Spring][]).flatMap(([name, s]) => {
    const sampled = sampleSpring(s);
    return [
      `  ${name}: {`,
      `    durationMs: ${sampled.durationMs},`,
      `    t95Ms: ${sampled.t95Ms},`,
      `    overshoot: ${sampled.overshoot},`,
      `    linear: '${sampled.linear}',`,
      `    cubicBezier: '${sampled.cubicBezier}',`,
      '  },',
    ];
  });
  return [
    `// ${GENERATED_BY}`,
    '',
    "import type { SpringName } from '../tokens';",
    '',
    '/** A spring\'s step response sampled at 60 Hz for the Web Animations API. `linear` is the CSS',
    ' *  `linear()` easing over `durationMs`, the settled duration; `cubicBezier` is the nearest',
    ' *  cubic-bezier, for engines without `linear()`; `t95Ms` is when it first reaches 95%; `overshoot` is',
    ' *  its peak past the target, as a fraction of the distance. */',
    'export interface SampledSpring {',
    '  readonly durationMs: number;',
    '  readonly t95Ms: number;',
    '  readonly overshoot: number;',
    '  readonly linear: string;',
    '  readonly cubicBezier: string;',
    '}',
    '',
    'export const SAMPLED_SPRINGS: Readonly<Record<SpringName, SampledSpring>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

function pageMjs(): string {
  return [
    `// ${GENERATED_BY}`,
    '',
    "// The runtime page's canvas before a theme brings its own `bg` (build/assemble.mjs): the light `bg`.",
    `export const PAGE_BG = '${COLORS.light.bg}';`,
    '',
  ].join('\n');
}

// ── Spring sampling ──────────────────────────────────────────────────────────

const FPS = 60;
/** Settled: within 0.1% of the distance, moving under 1% of it per second, from this frame on. */
const SETTLE_DISTANCE = 0.001;
const SETTLE_VELOCITY = 0.01;
const HORIZON_S = 5;

export interface SampledSpring {
  readonly durationMs: number;
  readonly t95Ms: number;
  readonly overshoot: number;
  readonly linear: string;
  readonly cubicBezier: string;
}

/** Position (0 → 1) and velocity at `t` seconds of a mass-1 spring released from rest. */
function stepResponse(s: Spring, t: number): [number, number] {
  const w = (2 * Math.PI) / s.response;
  const z = s.dampingRatio;
  if (z === 1) {
    const e = Math.exp(-w * t);
    return [1 - (1 + w * t) * e, w * w * t * e];
  }
  if (z < 1) {
    const wd = w * Math.sqrt(1 - z * z);
    const e = Math.exp(-z * w * t);
    return [1 - e * (Math.cos(wd * t) + ((z * w) / wd) * Math.sin(wd * t)), e * ((w * w) / wd) * Math.sin(wd * t)];
  }
  const root = w * Math.sqrt(z * z - 1);
  const r1 = -z * w + root;
  const r2 = -z * w - root;
  const e1 = Math.exp(r1 * t);
  const e2 = Math.exp(r2 * t);
  return [1 + (r2 * e1 - r1 * e2) / (r1 - r2), (r1 * r2 * (e1 - e2)) / (r1 - r2)];
}

const round3 = (n: number) => {
  const r = Math.round(n * 1000) / 1000;
  return r === 0 ? 0 : r;
};

function settledFrame(s: Spring): number {
  let last = 0;
  for (let f = 0; f <= HORIZON_S * FPS; f++) {
    const [x, v] = stepResponse(s, f / FPS);
    if (Math.abs(x - 1) >= SETTLE_DISTANCE || Math.abs(v) >= SETTLE_VELOCITY) last = f;
  }
  return last + 1;
}

function time95(s: Spring): number {
  let hi = 1 / FPS;
  while (stepResponse(s, hi)[0] < 0.95) hi += 1 / FPS;
  let lo = hi - 1 / FPS;
  for (let i = 0; i < 40; i++) {
    const mid = (lo + hi) / 2;
    if (stepResponse(s, mid)[0] < 0.95) lo = mid;
    else hi = mid;
  }
  return hi;
}

/** CSS cubic-bezier(x1, y1, x2, y2) at progress `u` (0–1). */
function bezierAt(p: readonly number[], u: number): number {
  const [x1, y1, x2, y2] = p;
  const coord = (a: number, b: number, s: number) => 3 * a * (1 - s) ** 2 * s + 3 * b * (1 - s) * s * s + s ** 3;
  let lo = 0;
  let hi = 1;
  for (let i = 0; i < 30; i++) {
    const mid = (lo + hi) / 2;
    if (coord(x1, x2, mid) < u) lo = mid;
    else hi = mid;
  }
  return coord(y1, y2, (lo + hi) / 2);
}

function fitError(p: readonly number[], samples: readonly number[]): number {
  const n = samples.length - 1;
  let sum = 0;
  for (let i = 0; i <= n; i++) sum += (bezierAt(p, i / n) - samples[i]) ** 2;
  return sum;
}

const FIT_STARTS = [
  [0.25, 0.5, 0.25, 1],
  [0.2, 0.9, 0.2, 1],
  [0.4, 0, 0.2, 1],
  [0.3, 1.3, 0.3, 1],
  [0.5, 0.5, 0, 1],
];

/** The cubic-bezier nearest the sampled curve (least squares), by a deterministic pattern search
 *  ending on the 0.01 grid it is printed at. A curve that never passes its target gets a bezier
 *  that never does either (both y control points at most 1). */
function nearestCubicBezier(samples: readonly number[]): string {
  const yMax = Math.max(...samples) > 1 ? Infinity : 1;
  const within = (v: number, hi: number) => Math.min(hi, Math.max(0, v));
  const clamp = (p: number[]) => [within(p[0], 1), Math.min(yMax, p[1]), within(p[2], 1), Math.min(yMax, p[3])];
  // The first of the eight one-coordinate moves of `step` that lowers the error, if any.
  const betterNeighbour = (from: number[], error: number, step: number): [number[], number] | undefined => {
    for (let k = 0; k < 4; k++) {
      for (const dir of [1, -1]) {
        const cand = clamp(from.map((v, i) => (i === k ? Math.round((v + dir * step) * 100) / 100 : v)));
        const e = fitError(cand, samples);
        if (e < error - 1e-12) return [cand, e];
      }
    }
    return undefined;
  };
  const descend = (start: number[]): [number[], number] => {
    let at: [number[], number] = [clamp(start), fitError(clamp(start), samples)];
    for (let step = 0.16; step >= 0.01 - 1e-9; step /= 2) {
      for (let next = betterNeighbour(at[0], at[1], step); next !== undefined; next = betterNeighbour(at[0], at[1], step)) at = next;
    }
    return at;
  };
  // Several starts, so a local minimum of one does not decide the curve; the lowest error wins.
  const [best] = FIT_STARTS.map(descend).reduce((a, b) => (b[1] < a[1] - 1e-12 ? b : a));
  return `cubic-bezier(${best.map((v) => String(Math.round(v * 100) / 100)).join(', ')})`;
}

const sampleCache = new Map<Spring, SampledSpring>();

/** A spring sampled at 60 Hz until it settles. */
export function sampleSpring(s: Spring): SampledSpring {
  const cached = sampleCache.get(s);
  if (cached !== undefined) return cached;
  const frames = settledFrame(s);
  const samples = Array.from({ length: frames + 1 }, (_, f) => (f === frames ? 1 : stepResponse(s, f / FPS)[0]));
  const z = s.dampingRatio;
  const sampled: SampledSpring = {
    durationMs: Math.round((frames * 1000) / FPS),
    t95Ms: Math.round(time95(s) * 1000),
    overshoot: z < 1 ? round3(Math.exp((-z * Math.PI) / Math.sqrt(1 - z * z))) : 0,
    linear: `linear(${samples.map((x) => String(round3(x))).join(', ')})`,
    cubicBezier: nearestCubicBezier(samples),
  };
  sampleCache.set(s, sampled);
  return sampled;
}

// ── Splicing and the drift check ─────────────────────────────────────────────

const REGIONS: Readonly<Record<string, Readonly<Record<string, () => string[]>>>> = {
  [SYSTEM_MD]: {
    roles: rolesTable,
    ember: emberTable,
    status: statusTable,
    tints: tintsTable,
    type: typeTable,
    space: spaceTable,
    layout: layoutTable,
    shape: shapeTable,
    shadows: shadowsTable,
    springs: springsTable,
    timings: timingsTable,
  },
  [MOCKUP_HTML]: { mockup: mockupBlock },
};

const WHOLE_FILES: Readonly<Record<string, () => string>> = {
  [PALETTE_JSON]: paletteJson,
  [SPRINGS_TS]: springsTs,
  [PAGE_MJS]: pageMjs,
};

/** Every file `npm run tokens` writes or splices, repo-relative. */
export const OUTPUT_FILES: readonly string[] = [...Object.keys(REGIONS), ...Object.keys(WHOLE_FILES)];

export interface Drift {
  readonly file: string;
  readonly region?: string;
  readonly message: string;
}

interface Span {
  readonly begin: number;
  readonly end: number;
}

function findRegion(lines: readonly string[], name: string): Span | undefined {
  const marker = (kind: string) => new RegExp(`tokens:${kind} ${name}(?![\\w-])`);
  const begin = lines.findIndex((l) => marker('begin').test(l));
  const end = lines.findIndex((l, i) => i > begin && marker('end').test(l));
  return begin < 0 || end < 0 ? undefined : { begin, end };
}

/** Where `actual` first departs from `expected`: for a Markdown table row, the row, the column and
 *  both cell values; otherwise the line and both texts. */
function describeDifference(expected: readonly string[], actual: readonly string[]): string {
  const i = expected.findIndex((line, k) => line !== actual[k]);
  const at = i < 0 ? expected.length : i;
  const want = expected[at];
  const got = actual[at];
  if (want === undefined) return `an extra line ${JSON.stringify(got)} the token module does not give`;
  if (got === undefined) return `a missing line; the token module gives ${JSON.stringify(want)}`;
  if (want.startsWith('|') && got.startsWith('|')) {
    const cells = (l: string) => l.split('|').slice(1, -1).map((c) => c.trim());
    const [w, g] = [cells(want), cells(got)];
    const col = w.findIndex((c, k) => c !== g[k]);
    if (col >= 0) {
      const columns = cells(expected[0]);
      return `row ${w[0]}, column "${columns[col] ?? col + 1}": the file has ${JSON.stringify(g[col] ?? '')}, the token module gives ${JSON.stringify(w[col])}`;
    }
  }
  return `line ${at + 1}: the file has ${JSON.stringify(got)}, the token module gives ${JSON.stringify(want)}`;
}

/** `text` with each of `regions` regenerated between its markers; a missing marker is a problem. */
function spliceRegions(file: string, text: string, regions: Readonly<Record<string, () => string[]>>, problems: Drift[]): string {
  let lines = text.split('\n');
  for (const [name, render] of Object.entries(regions)) {
    const span = findRegion(lines, name);
    if (span === undefined) problems.push({ file, region: name, message: `no "tokens:begin ${name}" … "tokens:end ${name}" markers` });
    else lines = [...lines.slice(0, span.begin + 1), ...render(), ...lines.slice(span.end)];
  }
  return lines.join('\n');
}

/** Each output file's generated text, given the current text of the files with marked regions
 *  (`read` returns undefined for a missing file). A missing file or marker is a drift. */
export function renderOutputs(read: (file: string) => string | undefined): { files: Record<string, string>; problems: Drift[] } {
  const files: Record<string, string> = {};
  const problems: Drift[] = [];
  for (const [file, regions] of Object.entries(REGIONS)) {
    const text = read(file);
    if (text === undefined) problems.push({ file, message: 'the file is missing' });
    else files[file] = spliceRegions(file, text, regions, problems);
  }
  for (const [file, render] of Object.entries(WHOLE_FILES)) files[file] = render();
  return { files, problems };
}

/** Every output that differs from what the token module gives, naming where and both values. */
export function checkOutputs(read: (file: string) => string | undefined): Drift[] {
  const { files, problems } = renderOutputs(read);
  const drifts = [...problems];
  for (const [file, expected] of Object.entries(files)) {
    const actual = read(file);
    if (actual === expected) continue;
    if (actual === undefined) {
      drifts.push({ file, message: 'the file is missing' });
      continue;
    }
    const regions = REGIONS[file];
    if (regions === undefined) {
      drifts.push({ file, message: describeDifference(expected.split('\n'), actual.split('\n')) });
      continue;
    }
    const [want, got] = [expected.split('\n'), actual.split('\n')];
    for (const name of Object.keys(regions)) {
      const w = findRegion(want, name);
      const g = findRegion(got, name);
      if (w === undefined || g === undefined) continue;
      const wantBody = want.slice(w.begin + 1, w.end);
      const gotBody = got.slice(g.begin + 1, g.end);
      if (wantBody.join('\n') !== gotBody.join('\n')) drifts.push({ file, region: name, message: describeDifference(wantBody, gotBody) });
    }
  }
  return drifts;
}

/** One line per drift, for the CLI and the gate. */
export function formatDrift(d: Drift): string {
  const where = d.region === undefined ? d.file : `${d.file} [${d.region}]`;
  return `${where}: ${d.message}`;
}
